# Processing SBE data with pIMOS

Included instruments:
- SBE56
- SBE39 T
- SBE39 TP
- SBE37 CTD
- And of course our very special friend, SBE37 4567 CT


In [1]:
# import seabird as sbd
# import crude_readers.read.SEABIRD_37_39_56 as read_sbd

import pIMOS.xrwrap.SEABIRD_37_39_56 as wrap_sbd
from pIMOS.xrwrap.NORTEK_VECTOR import NORTEK_VECTOR, num2date_lk
from pIMOS.xrwrap.NORTEK_SIGNATURE import NORTEK_SIGNATURE
from pIMOS.xrwrap.WETLABS_NTU import WETLABS_NTU, parse_device_file

import os
import matplotlib.pyplot as plt
import datetime
import numpy as np 
import pandas as pd
import glob

import pIMOS.utils.quality_control as pqc
import importlib

# O Drive is //drive.irds.uwa.edu.au/CEME-BBL-001
# pIMOS_export_dir = r'O:\Data\pIMOS\KISSME'

project_root = r'G:\Experiments\kissme17'
archive_dir = os.path.join(project_root, 'archive_FV00') 
dbconfig_file = os.path.join('./', 'database', 'config.txt') 

if not os.path.exists(archive_dir):
    os.mkdir(archive_dir)
    

<class 'datetime.datetime'>
Module tested
<class 'datetime.datetime'>
Time vector is well spaced
<class 'numpy.datetime64'>
Time vector is well spaced
There are 101 elements in this 10 second period spaced at 0.1.
Time Module OK
[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


c:\users\azulberti\dropbox\university\phd\03_code\source_code\turbo_tools\turbo_tools\utils\time.py:182: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  ans = linspacetime(pd.datetime.today(), pd.datetime.today()+datetime.timedelta(1), n=100)
c:\users\azulberti\dropbox\university\phd\03_code\source_code\turbo_tools\turbo_tools\utils\time.py:189: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  ans = linspacetime(pd.datetime.today(), pd.datetime.today()+dt, dt_s=dt_s)


Time vector is well spaced
Time vector is well spaced
There are 101 elements in this 10 second period spaced at 0.1.
Time Module OK


c:\users\azulberti\dropbox\university\phd\03_code\source_code\zutils\zutils\time.py:217: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  ans = linspacetime(pd.datetime.today(), pd.datetime.today()+datetime.timedelta(1), n=100)
c:\users\azulberti\dropbox\university\phd\03_code\source_code\zutils\zutils\time.py:224: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  ans = linspacetime(pd.datetime.today(), pd.datetime.today()+dt, dt_s=dt_s)


# Import info and utilities to help with the archiving

In [2]:
import archive_info_and_utils as ai

db_config = ai.parse_dbconfig(dbconfig_file)
db_data = ai.read_db(dbconfig_file)
db_config
db_data

deployment_metadata = KISSME_Instruments.csv

possible_mooring_dates = possible_mooring_dates.csv
deployment_metadata = KISSME_Instruments.csv

possible_mooring_dates = possible_mooring_dates.csv


{'deployment_metadata':     StationID  Longitude  Latitude  Depth TimeZone            Site  \
 0      BRB200   123.0459  -14.2426   -200      UTC    Browse Shelf   
 1      BRB200   123.0459  -14.2426   -200      UTC    Browse Shelf   
 2      BRB200   123.0459  -14.2426   -200      UTC    Browse Shelf   
 3      BRB200   123.0459  -14.2426   -200      UTC    Browse Shelf   
 4      BRB200   123.0459  -14.2426   -200      UTC    Browse Shelf   
 ..        ...        ...       ...    ...      ...             ...   
 126     WP250   123.3490  -13.7659   -252      UTC  Browse Prelude   
 127     WP250   123.3490  -13.7659   -252      UTC  Browse Prelude   
 128     WP250   123.3490  -13.7659   -252      UTC  Browse Prelude   
 129     WP250   123.3490  -13.7659   -252      UTC  Browse Prelude   
 130     WP250   123.3490  -13.7659   -252      UTC  Browse Prelude   
 
      InstrumentDepth                      FileName            FilePath  \
 0             -193.1                  6752_000.

# Loop through all now using the spreadsheet

# Now the LISST
Need code from Will


In [4]:
import pIMOS.read.lisst as read_lisst
import os, importlib 
import pandas as pd

importlib.reload(read_lisst)

lisst_direc = r'D:\Experiments\kissme17\LISST\2031'
lisst_csv = 'L0910204.csv'

lisst_full = os.path.join(lisst_direc, lisst_csv)

In [5]:
from pIMOS.xrwrap import LISST

rr = LISST.LISST(lisst_direc, lisst_csv, method='csv')

Setting default attributes of the class.
Setting attribute "title" to "Measured data from a Seabird Data Logger"
Setting attribute "source" to "Seabird Data Logger"
Setting attribute "history" to ""
Setting attribute "comment" to ""


In [6]:
rr

In [26]:

direc = os.path.split(lisst_csv)[0]
direc

fields, units, dtype, bins_lower, bins_median = read_lisst.load_LISST_info(direc)
df = pd.read_csv(lisst_csv, header=None)
time_series = read_lisst.convert_LISST_time(df)
df = read_lisst.add_LISST_flags(df)
ds = read_lisst.parse_LISST_csv(df, fields, units, dtype, bins_lower)
